---
title: "p8105_hw5_lz2949"
author: "Longyi Zhao"
date: "2023-11-03"
output: github_document
---

```{r}
library(tidyverse)
library(broom)
library(ggplot2)
```

## Problem 1
```{r}
homi_data = read_csv(file = "./data/homicide-data.csv")
```

```{r}
# Create a city_state variable
homi_data  = 
  homi_data |>
  mutate(city_state = paste(city,state,sep = ", "))

# summary and count number of homicides 
summary_data = homi_data |>
  group_by(city_state) |>
  summarise(
    homi_solved = sum(disposition == 'Closed by arrest'),
    homi_unsolved = sum(disposition == 'Open/No arrest' | disposition == 'Closed without arrest')
  )

```
Description: 

```{r}
# in 'Baltimore, MD' estimate the proportion of homicides that are unsolved. 
balt_md = summary_data |>
  filter(city_state == "Baltimore, MD") |>
  mutate(sum_homi = sum(homi_solved, homi_unsolved)) |>
  do ({prop.test(.$homi_unsolved, .$sum_homi) |>
  broom::tidy() })|>
  select(estimate, conf.low, conf.high) |>
  mutate(city_state = "Baltimore, MD") 
```

```{r}
# run prop.test for each of the city
result_df <- summary_data |>
  group_by(city_state) |>
  summarize(prop_test_results = map(homi_unsolved, ~ prop.test(.x, .x +homi_solved) |>
  broom::tidy())) |>
  unnest(prop_test_results) |>
  select(city_state, estimate, conf.low, conf.high) 

print(result_df)
```

```{r}
ggplot(result_df, aes(x = city_state, 
                      y = estimate, 
                      color = city_state
                      )) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  labs(
    title = "Estimated Proportions and Confidence Intervals by City",
    x = "City",
    y = "Estimated Proportion of Unsolved Homicides"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme(legend.position = "none")

# drop legend?
```
description 

## Problem 2
```{r}
# a dataframe containign all file names
data_directory = "./datap2"
file_names = list.files(path = data_directory, full.names = TRUE, pattern = ".csv")

# iterate over file names and read in data for each subject using map and save rthe result
data_list = map(file_names, ~ read.csv(.x) |>
                  mutate(subject_id = basename(.x)) |>
                  separate(subject_id, c("subject_id", "arm"), sep = "_"))

# tidy the result
tidy_data = bind_rows(data_list) |>
  rename(test_arm = subject_id, test_id = arm) |>
  mutate(test_id = sub( "\\.csv$", "", test_id)) |>
  pivot_longer(cols = starts_with("week_"), names_to = "time", values_to = "value")

```

```{r}
# make a spaghetti plot showing observations on each subject over time
ggplot(tidy_data, 
       aes(x = time, y = value, group = test_id, color = test_id)) +
  geom_point() +
  geom_line() +
  facet_wrap(.~test_arm) +
  labs(
    title = "Spaghetti Plot of Observations Over Time",
    x = "Time",
    y = "Value",
    color = "Subject ID"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```
description: 

## Problem 3
